version: '3.4'

services:
  basicsingleclientweb:
    image: ${DOCKER_REGISTRY-}basicsingleclientweb
    build:
      context: .
      dockerfile: BasicSingleClientWeb/Dockerfile
    environment:
      SQL_USERNAME: sa
      SQL_PASSWORD: Your_password123
      SQL_SERVER: sql-tenant1
  sql:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"