name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet build LowKey.sln
  test: 
    runs-on: self-hosted
    needs: [build]
    steps:
      - name: Test
        run: dotnet test LowKey.sln --no-build --verbosity normal
  publish: 
    runs-on: self-hosted
    needs: [Test]
    steps:
      - name: Publish Nuget Packages
        run: |
            dotnet pack LowKey.Data/LowKey.Data.csproj
            dotnet pack LowKey.Data.Sql/LowKey.Data.Sql.csproj
            dotnet pack LowKey.Extensions.Hosting/LowKey.Extensions.Hosting.csproj
