name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet build LowKey.sln
  test: 
    runs-on: self-hosted
    needs: [build]
    steps:
      - name: Test
        run: dotnet test LowKey.sln --no-build --verbosity normal
  publish: 
    runs-on: self-hosted
    needs: [Test]
    steps:
      - name: Publish Nuget Packages
        run: |
            $branch = ${{github.head_ref}}

            $prerelease = ""

            if($branch -ne "main") {
                $prerelease = $branch.Replace("/", "-")
            }

            Write-Host "Branch: $branch"
            Write-Host "Pre-Release: $prerelease"

            if($prerelease) {
                dotnet pack LowKey.Data/LowKey.Data.csproj -c Release --no-build --no-restore --version-suffix $prerelease
                dotnet pack LowKey.Data.Sql/LowKey.Data.Sql.csproj -c Release --no-build --no-restore --version-suffix $prerelease
                dotnet pack LowKey.Extensions.Hosting/LowKey.Extensions.Hosting.csproj -c Release --no-build --no-restore --version-suffix $prerelease
            } else {
                dotnet pack LowKey.Data/LowKey.Data.csproj -c Release --no-build --no-restore
                dotnet pack LowKey.Data.Sql/LowKey.Data.Sql.csproj -c Release --no-build --no-restore
                dotnet pack LowKey.Extensions.Hosting/LowKey.Extensions.Hosting.csproj -c Release --no-build --no-restore
            }
